<Root>:
    rows: 1

    BoxLayout:
        orientation: "vertical"

        BoxLayout:
            orientation: "horizontal"

            BoxLayout:
                orientation: "vertical"

                Clock:
                    text: "Clock"

                Weather:
                    text: "Weather"

            BoxLayout:
                orientation: "vertical"

                Calendar:
                    text: "Date/Calendar"

                Events:
                    text: "Events"

        BoxLayout:
            orientation: "horizontal"

            BoxLayout:
                orientation: "vertical"

                ExchangeRates:
                    text: "Currents"

                News:
                    text: "News"

            BoxLayout:
                orientation: "vertical"

                Mail:
                    text: "Mail"


