#: import fs app.frames.utilities.FontSize

<Currency>:
    orientation: "horizontal"

    MonoLabel:
        size_hint: (.7, 1)
        font_size: fs.MEDIUM
        text: "DBG: "

    MonoLabel:
        font_size: fs.MEDIUM
        text: "debug"

<ExchangeRates>:

    orientation: "vertical"

    MonoLabel:
        font_size: fs.BIG
        id: currency
        text: "UAH:"

    BoxLayout:
        orientation: "vertical"
        id: currencies
